name = "dockrx"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
minify = true

[vars]
NODE_ENV = "production"

[secrets]
required = [
  "MONGODB_URI",
  "JWT_SECRET",
  "ADMIN_EMAIL",
  "ADMIN_PASSWORD",
  "CURRENCY",
  "RAZORPAY_KEY_ID",
  "RAZORPAY_KEY_SECRET",
  "STRIPE_SECRET_KEY",
  "FRONTEND_URL",
  "ADMIN_URL",
]

[[kv_namespaces]]
binding = "IMAGES_KV"
id = "05d74f39db0f457dbe9f27ca7b55a9a2"
